app = "personodered33"
primary_region = "scl"

[build]
  image = "nodered/node-red:latest"

[[services]]
  internal_port = 1880
  processes = ["app"]
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
